import React,{useState}from'react';
import{AlertCircle,Calendar,Eye,Heart,Image,MessageSquare,Monitor,Plus,Send,User,Users,Video}from'lucide-react';
import'./community.css';
const tabs=[['forum','Forum',Users],['live','Live Trade',Monitor],['chat','Chat',MessageSquare],['info','Info',AlertCircle]];
const seedPosts=[['Arief S.','SULTAN'],['Dimas P.','PRIME'],['Nanda F.','ELITE'],['Varabi S.','']];
const seedNotices=[['NFP High Impact — Hari Ini','2 Jam Lalu'],['NFP High Impact — Hari Ini','2 Jam Lalu'],['NFP High Impact — Hari Ini','2 Jam Lalu'],['Reward Program Juli 2026 Dibuka','1 Hari Lalu'],['Reward Program Juli 2026 Dibuka','1 Hari Lalu'],['Reward Program Juli 2026 Dibuka','1 Hari Lalu']];
function Header({active,setActive}){return <section className="community-header"><h1>COMMUNITY</h1><nav>{tabs.map(([id,label,Icon])=><button className={active===id?'active':''} onClick={()=>setActive(id)} key={id}><Icon/>{label}</button>)}</nav></section>}
function Avatar({gold=false}){return <span className={`community-avatar ${gold?'gold':''}`}><User/></span>}
function MemberCard({name,tier,text='Setup SELL XAUUSD Di Area 3428–3430 Masih Valid. Konfirmasi H1 Engulfing, SL Maintain 3438.'}){const[liked,setLiked]=useState(false);return <article className="member-card"><div><Avatar/><h3>{name}</h3>{tier&&<b className={tier.toLowerCase()}>{tier}</b>}</div><p>{text}</p><small><button className="bare-action" onClick={()=>setLiked(!liked)}><Heart fill={liked?'#d90008':'none'}/>{liked?94:93}</button><MessageSquare fill="#fff"/>29</small></article>}
function Forum(){const[text,setText]=useState('');const[posts,setPosts]=useState(seedPosts);return <section className="forum-view"><div className="forum-main"><h2><Calendar/> COMMUNITY FORUM</h2><div className="forum-composer"><textarea placeholder="Tulis Di Forum..." value={text} onChange={e=>setText(e.target.value)}/><div><label className="file-action"><Image/>Foto<input hidden type="file" accept="image/*"/></label><label className="file-action"><Video/>Video<input hidden type="file" accept="video/*"/></label><button onClick={()=>{if(text.trim()){setPosts([['Naufal H.','PRIME',text],...posts]);setText('')}}}>Kirim <Send/></button></div></div>{posts.map((x,i)=><MemberCard name={x[0]} tier={x[1]} text={x[2]} key={`${x[0]}-${i}`}/>)}</div><aside><h2><Calendar/> TRENDING</h2>{[1,2,3].map(x=><article key={x}><b>NFP Discussion</b><span><Eye/>1.2K Views</span></article>)}</aside></section>}
function LivePost({name='Varabi S.',tier='SULTAN',right=false,admin=false,text}){return <article className={`live-post ${right?'right':''} ${admin?'admin':''}`}><div><Avatar gold={admin}/><h3>{name}</h3><b className={tier.toLowerCase()}>{tier}</b><time>09:42</time></div><p>{text||'Setup SELL XAUUSD Di Area 3428–3430 Masih Valid. Konfirmasi H1 Engulfing, SL Maintain 3438.'}</p></article>}
function CommentBox({onSend}){const[value,setValue]=useState('');return <label className="comment-box"><input placeholder="Tulis Komentar..." value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&value.trim()){onSend(value);setValue('')}}}/><button onClick={()=>{if(value.trim()){onSend(value);setValue('')}}}><Send/></button></label>}
function LiveTrade(){const[comments,setComments]=useState([]);const[inputUrl,setInputUrl]=useState('https://www.youtube.com/watch?v=jfKfPfyJRdk');const[liveUrl,setLiveUrl]=useState('https://www.youtube.com/embed/jfKfPfyJRdk');const toEmbed=url=>{const match=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|live\/))([\w-]{6,})/);return match?`https://www.youtube.com/embed/${match[1]}`:''};const publish=()=>{const embed=toEmbed(inputUrl);if(!embed)return window.alert('Enter a valid YouTube video or live URL.');setLiveUrl(embed)};return <section className="live-view"><div className="live-manage"><h2>LIVE MANAGE</h2><div className="youtube-admin"><input aria-label="YouTube live URL" value={inputUrl} onChange={e=>setInputUrl(e.target.value)} placeholder="Paste YouTube live link..."/><button onClick={publish}>Publish Live</button></div></div><div className="live-screen"><span>● LIVE</span><span><Eye/>{283+comments.length}</span><iframe src={liveUrl} title="NH Terminal live trade demo" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><div className="live-feed"><LivePost/><LivePost/><LivePost name="Chesta" tier="PRIME" right/>{comments.map((x,i)=><LivePost name="Naufal H." tier="PRIME" right text={x} key={i}/>)}<LivePost name="Admin NH" admin/><CommentBox onSend={x=>setComments([...comments,x])}/><i className="fake-scroll"/></div></section>}
function Chat(){const[conversation,setConversation]=useState('Admin NH');const[messages,setMessages]=useState(['Halo Admin, Mau Tanya Soal Upgrade Tier Ke Elite']);return <section className="chat-view"><aside><h2>CONVERSATIONS</h2>{[['Admin NH','2 New Messages'],['Support',''],['Trading Room','']].map(([name,note],i)=><button onClick={()=>setConversation(name)} className={conversation===name?'selected':''} key={name}><Avatar gold={i===0}/><span><b>{name}</b>{note&&<small>{note}</small>}</span></button>)}</aside><div className="chat-room"><span className="today">Today · {conversation}</span><div className="bubble received">Selamat Datang Di NH Terminal! Ada Yang Bisa Kami Bantu?</div>{messages.map((x,i)=><div className="bubble sent" key={i}>{x}</div>)}<div className="bubble received">Pesan demo diterima. Tim kami akan segera membalas.</div><CommentBox onSend={x=>setMessages([...messages,x])}/></div></section>}
function Notice({title,age}){return <article className="notice"><h3>{title}</h3><time>15:30 WIB</time><p>Volatilitas Estimasi 80–150 Pips. Rekomendasi Close Posisi Atau Perlebar SL Minimal 50 Pips.</p><small>{age}</small><b>Admin NH</b></article>}
function InfoView(){const[title,setTitle]=useState('');const[body,setBody]=useState('');const[notices,setNotices]=useState(seedNotices);return <section className="info-view"><div className="announcement-form"><div><h2>ANNOUNCEMENTS</h2><button onClick={()=>document.querySelector('.announcement-form input')?.focus()}><Plus/>Create Announcement</button></div><input placeholder="Judul Pengumuman" value={title} onChange={e=>setTitle(e.target.value)}/><div className="announcement-body"><textarea placeholder="Isi Pengumuman" value={body} onChange={e=>setBody(e.target.value)}/><label className="file-action"><Image/>Foto<input hidden type="file" accept="image/*"/></label><button onClick={()=>{if(title.trim()&&body.trim()){setNotices([[title,'Baru saja'],...notices]);setTitle('');setBody('')}}}>Publish <Send/></button></div></div><div className="notices">{notices.map((x,i)=><Notice title={x[0]} age={x[1]} key={i}/>)}</div></section>}
export default function CommunityPage(){const[active,setActive]=useState('forum');return <div className="community-page"><Header active={active} setActive={setActive}/>{active==='forum'&&<Forum/>}{active==='live'&&<LiveTrade/>}{active==='chat'&&<Chat/>}{active==='info'&&<InfoView/>}</div>}
